### ISSUE TITLE
Studio update site

### ISSUE THREAD

**Issue by manikmagar** [rbutenuth/assert-object-equals-connector#2]
Where can I find studio update site archive? URL in the read me is throwing 400 error. Can you attach it to release? Something like this - [mule-couchbase-connector-1.0.0](https://github.com/manikmagar/mule-couchbase-connector/releases/tag/mule-couchbase-connector-1.0.0)

Generated [UpdateSite.zip](https://github.com/rbutenuth/assert-object-equals-connector/files/1288241/UpdateSite.zip)  for 0.0.6.

**Comment by ildede** [comment]
Don't use a browser to go to that url.
You need to put that in "AnypointStudio -> Help -> Install new Software"
And the connector will appear in the list.
