### ISSUE TITLE
Are you still supporting this?

### ISSUE THREAD

**Issue by aoathout** [rbutenuth/assert-object-equals-connector#3]
We have been using this connector and it has saved us a lot of time and made our tests cleaner and easier. I see you haven't done much with this for 2 yrs. Its been stable for us so maybe you had no need to. Do you plan on supporting this in the future? would you like some collaborators?

**Comment by rbutenuth** [comment]
Yes to both questions. If you have ideas to improve it: Just start!

**Comment by rbutenuth** [comment]
Just released 1.0.0
