### ISSUE TITLE
Unable to ignore fields in root map

### ISSUE THREAD

**Issue by timechanter** [rbutenuth/assert-object-equals-connector#6]
Is there a trick for Ignoring a simple String key in the root of a map? I can't seem to have it validate correctly two objects (maps) where the only difference is a single key that I wish to ignore.

**Comment by rbutenuth** [comment]
Hi!

Have a look at https://github.com/rbutenuth/assert-object-equals-connector/blob/master/docs/compare-objects.md

To ignore one toplevel "key" in the rootmap use:

```
<assert-object-equals:path-options>
    <assert-object-equals:path-option>['key'] ignore</assert-object-equals:path-option>
</assert-object-equals:path-options>
```
